### ISSUE TITLE
Missing text in "Fun with MediaSource composition"

### ISSUE THREAD

**Issue by qzo** [googlecodelabs/exoplayer-intro#3]
On the "Fun with MediaSource composition" page, some text (probably about LoopingMediaSource) seems to be missing:

> Given we want to play our mp3 file endlessly,

**Comment by marcbaechinger** [comment]
Thanks for reporting!

I removed this text which is obsolete. Will be pushed to production soon.

BTW: Best approach to let the player loop playback is using the repeat mode instead of using a specific MediaSource (like Looping). Repeat mode is built in to the player and works with arbitray MediaSources.
