### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by OlegarioLopez** [googlecodelabs/exoplayer-intro#48]
1º- In step 2  (Getting set up) it says: The exoplayer-codelab-NN folders contain the desired end state of each step of this codelab.
But that folders don´t exist.

2º- In step 3 if you follow this Pro tip: Use Android Studio's Quick Fix feature to add a member field automatically.
Android Studio create a View not a PlayerView as desired.

**Comment by dturner** [comment]
Thanks for helping to improve the codelab! 

> 1º- In step 2 (Getting set up) it says: The exoplayer-codelab-NN folders contain the desired end state of each step of this codelab.
> But that folders don´t exist.

The `NN` part refers to the `00` to `04` in the folder name. I have updated the instructions to make this clearer. 

> 2º- In step 3 if you follow this Pro tip: Use Android Studio's Quick Fix feature to add a member field automatically.
Android Studio create a View not a PlayerView as desired.

I've added a note to that section "Remember to set the type to `PlayerView` rather than the default `View.`"
