### ISSUE TITLE
In "initializePlayer", the player should be prepared before setting the playback state values

### ISSUE THREAD

**Issue by rabyunghwa** [googlecodelabs/exoplayer-intro#49]
In `initializePlayer`:
```
private void initializePlayer() {
    [...]
    player.setPlayWhenReady(playWhenReady);
    player.seekTo(currentWindow, playbackPosition);
    player.prepare(mediaSource, false, false);
}
```
the player should be prepared _before_ setting the playback position and `playWhenReady` state values.

**Comment by dturner** [comment]
Thanks for filing this. Are you seeing unexpected behaviour in the codelab because of preparing the player _after_ setting state? 

The reason I ask is because the method signature for `prepare` is

```
public void prepare(MediaSource mediaSource,
                    boolean resetPosition,
                    boolean resetState)
```

Both `resetPosition` and `resetState` are set to `false` so any player state shouldn't be reset by the `prepare` operation.

**Comment by rabyunghwa** [comment]
Hello! It seems that the player's playback state cannot be properly restored if the player is prepared _after_ the playback state values are set.

**Comment by dturner** [comment]
I tested it on a Pixel 2 running Android 11 beta 2 and the playback position and state are preserved between orientation changes:
![exoplayer-intro-issue49](https://user-images.githubusercontent.com/873212/87407536-357a0700-c5ba-11ea-8c23-d42ed1f851c5.gif)

Is it the position, state or both which aren't preserved for you? Also, what device and Android build are you testing on?

**Comment by rabyunghwa** [comment]
Hello!

I didn't realize that in the manifest file, **android:configChanges="keyboard|keyboardHidden|orientation|screenSize|screenLayout|smallestScreenSize|uiMode"** was set. 

Well, if the app process was shut down due to resource constraints, then the player state wouldn't be properly restored (Nexus 5X, API 29):

![20200714_183739](https://user-images.githubusercontent.com/7411385/87410409-3b470b00-c601-11ea-8bee-a12c335b1c81.gif)

Sometimes it wouldn't work even if I saved the values in **onSaveInstanceState**. Sometimes it would work, though. Not sure if this is a platform bug or ExoPlayer-specific issue.

**Comment by dturner** [comment]
Thanks for the info. 

> Well, if the app process was shut down due to resource constraints, then the player state wouldn't be properly restored

Yes, that's true but I would assume that's because the fields (`playWhenReady` etc) would be reinitialized after the Activity is recreated. 

I still don't understand how the ordering of `prepare` changes that behaviour though. Or are you saying it doesn't change the behaviour and that we have a separate issue with `onSaveInstanceState`?

**Comment by rabyunghwa** [comment]
Actually I experimented with this several times before and I was able to fix the issue by changing the ordering. I'll follow up with a working sample that can demonstrate this.

**Comment by rabyunghwa** [comment]
Hello!

[Here](https://drive.google.com/file/d/1pyZ2NBNeL8trgarI5mihHEacVGN1ysov/view?usp=sharing) is the sample project.

There seems to be a platform bug of the passed in **savedInstanceState** bundle being **null** for the first process shutdown after app launch (which is another issue). Anyways, afterwards, the player's playback state just wouldn't be restored if the player was prepared _after_ setting the state values, as shown in the video below:

![20200714_223442](https://user-images.githubusercontent.com/7411385/87432664-457a0100-c623-11ea-842e-78a0571bb1d1.gif)

And the issue can be resolved by changing the ordering, as shown in the screenshot below:

![20200714_223348](https://user-images.githubusercontent.com/7411385/87432617-35fab800-c623-11ea-8bc7-d22b0a1e757d.gif)

**Comment by dturner** [comment]
In your `PlayerFragment` you have the line: `player.prepare(mediaSource,true, true);` which will reset both playback position and state.

In the codelab this line is `player.prepare(mediaSource, false, false);`

Could that account for the behaviour you're seeing?

**Comment by rabyunghwa** [comment]
Missed that! Thanks! Regarding that platform bug, where can I seek help?

**Comment by dturner** [comment]
I'm pleased that you found the source of your problem. In future, please ensure that any issues are reproducible **in the codelab** rather than your own project.  

For Android platform related issues you can [file bugs here](https://source.android.com/setup/contribute/report-bugs#bug-queues). I'd suggest using the "Framework" component for the issue you describe.
